site_name: Dimsum
site_url: http://dimsum.github.io
theme: 
  name: readthedocs
  highlightjs: true
  h1js_languages:
    - yaml
    - bash
  logo: images/favicon.ico
nav:
  - About: index.md
  # - Getting Started:
  #   - Requirements:
  #   - Configuration:
  #   - Building and Running:
  #   - Monitoring:
  # - User Manual:
  #   - Introduction:
  #     - History:
  #   - Site Configuration:
  #   - General Navigation:
  #     1. Logging In:
  #     2. Issue Tracking:

