management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
      base-path: "/"
      path-mapping:
        prometheus: "metrics"

spring:
  autoconfigure:
    exclude:
      # Disable UserDetailsServiceAutoConfiguration to prevent auto-creation of a test user
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  security:
    filter:
      dispatcher-types: request,async,error,forward,include
    saml2:
      relyingparty:
        registration:
          dimsum:
            signing.credentials:
              - private-key-location: file://${saml.spkey}
                certificate-location: file://${saml.spcert}
            identityprovider:
              entity-id: ${saml.idpid}
              verification.credentials:
                - certificate-location: file://${saml.idpcertificate}
              singlesignon.url: ${saml.ssourl}

build:
  version: "@project.version@"

server:
  error:
    path: /error
