management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
      base-path: "/"
      path-mapping:
        prometheus: "metrics"

spring:
  autoconfigure:
    exclude:
      # Disable UserDetailsServiceAutoConfiguration to prevent auto-creation of a test user
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  security:
    saml2:
      relyingparty:
        registration:
          dimsum:
            signing.credentials:
              - private-key-location: file://${saml.spkey}
                certificate-location: file://${saml.spcert}
            assertingparty:
              entity-id: ${saml.idpid}
              metadata-uri: ${saml.idpmetadataurl}
              verification.credentials:
                - certificate-location: file://${saml.idpcertificate}
              sso.url: ${saml.ssourl}
            singlelogout:
              url: "{baseUrl}/logout/saml2/slo"
              binding: POST

build:
  version: "@project.version@"

server:
  error:
    path: /error
