name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - run: mvn --batch-mode package
